Json_response/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='password'),

]

Json_response/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/update/', views.update, name='update'),
    path('<int:movie_pk>/delete/', views.delete, name='delete'),
    path('<int:movie_pk>/comment/', views.comment, name='comment'),
    path('<int:movie_pk>/comment/<int:comment_pk>/delete', views.comment_delete, name='comment_delete'),
    path('data/', views.data_response, name='data_response'),
]

Json_response/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include
from movies import views



urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

Json_response/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

Json_response/movies/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=20)
    description = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
class Comment(models.Model):
    content = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='commentall')

Json_response/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields

class CustomUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('username',)

Json_response/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from .forms import CustomUserCreationForm, CustomUserChangeForm

# Create your views here.
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('movies:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)

    return redirect('movies:index')



def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('movies:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)

def update(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = CustomUserChangeForm(request.POST, instance=request.user)
            if form.is_valid():
                form.save()
                return redirect('movies:index')
        else:
            form = CustomUserChangeForm(instance=request.user)
        context = {
            'form': form,
        }
        return render(request, 'accounts/update.html', context)
    return redirect('movies:index')

def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('movies:index')

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('movies:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)

Json_response/movies/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from .form import MovieForm, CommentForm
from .models import Movie, Comment

# Create your views here.
def index(request):
    movies = Movie.objects.all()

    context = {
        'movies': movies,
    }
    return render(request, 'movies/index.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = MovieForm(request.POST)
        if form.is_valid():
            movie = form.save(commit=False)
            movie.user = request.user
            movie.save()
            return redirect('movies:index')
    else:
        form = MovieForm()
    
    context = {
        'form': form,
    }
    return render(request, 'movies/create.html', context)

def detail(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    comments = movie.commentall.all()
    form = CommentForm()

    context = {
        'movie': movie,
        'form': form,
        'comments': comments,
    }
    return render(request, 'movies/detail.html', context)

@login_required
def update(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    if request.method == 'POST':
        form = MovieForm(request.POST, instance=movie)
        if form.is_valid():
            form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm(instance=movie)
    context = {
        'form': form,
        'movie': movie,
    }
    return render(request, 'movies/update.html', context)

@login_required
def delete(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    if request.method == 'POST':
        if request.user == movie.user:
            movie.delete()
            return redirect('movies:index')
    return redirect('movies:detail', movie.pk)

@login_required
def comment(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.movie = movie
            comment.save()
            return redirect('movies:detail', movie.pk)

    return redirect('movies:detail', movie.pk)
            
@login_required
def comment_delete(request, movie_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.method == 'POST':
        if request.user == comment.user:
            comment.delete()
    return redirect('movies:detail', movie_pk)


def data_response(request):
    movies = {
        '일': '위대한쇼맨', 
        '이': '어벤져스',
        '삼': '페이커',
        }

    context = {
        'name': '한',
        'movies': movies
    }

    return JsonResponse(context)

Json_response/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
  <h1>비밀번호 변경</h1>
  <form action="{% url 'accounts:password' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="변경">
  </form>
  <a href="{% url 'movies:index' %}">뒤로가기</a>
{% endblock content %}

Json_response/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<h1>Login</h1>
<form action="{% url 'accounts:login' %}" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="로그인">
</form>

<a href="{% url 'movies:index' %}">뒤로가기</a>
{% endblock content %}

Json_response/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<h1>회원가입페이지</h1>
<form action="{% url 'accounts:signup' %}" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="가입하기">
</form>

{% endblock content %}

Json_response/accounts/templates/accounts/update.html
{% extends 'base.html' %}


{% block content %}
<form action="{% url 'accounts:update' %}">
  {{ form.as_p }}
  <input type="submit" value="수정하기">
</form>
{% endblock content %}

Json_response/movies/templates/movies/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>create</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="생성하기">
  </form>
  <a href="{% url 'movies:index' %}">뒤로가기</a>
{% endblock content %}

Json_response/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>detail</h1>
  <p>{{ movie.title }}</p>
  <p>{{ movie.description }}</p>
  <hr>
  {% for comment in comments %}
    <div style="display: flex;">
      <div>{{ comment.user }}
        :
        {{ comment.content }}</div>
      {% if request.user == comment.user %}
        <form style="margin-left: 10px;" action="{% url 'movies:comment_delete' movie.pk comment.pk %}" method="POST">
          {% csrf_token %}
          <input type="submit" value="삭제">
        </form>
      {% endif %}
    </div>
    {% empty %}
    <span>댓글이 없음 ㅋ</span>
  {% endfor %}
  <hr>
  <form action="{% url 'movies:comment' movie.pk %}" method="POST">
    {% csrf_token %}
    {{ form }}
      <input type="submit" value="댓글달기">
    </form>

    <a href="{% url 'movies:index' %}">뒤로가기</a>
    <a href="{% url 'movies:update' movie.pk %}">수정하기</a>
    <form action="{% url 'movies:delete' movie.pk %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="삭제하기">
    </form>
  {% endblock content %}

Json_response/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
<style>
  .pagination{display:flex;}
  .pagination div{
    min-width:30px;
    padding:5px;
    border:solid 1px;
    border-radius:5px;
    text-align:center;
    cursor:pointer;
  }
  .pagination div:hover{
    background:skyblue;
  }

  #movie-title{
    display:flex;
    flex-wrap:wrap;
  }
  #movie-title > div{
    min-width:200px;
    max-width:200px;
    text-overflow:ellipsis;
    min-height:100px;
    background:gainsboro;
    margin:0px 1px 1px 0px;

    display: flex;
    align-items: center;
    justify-content: center;
    flex-direction: column;
  }

  #movie-title > div img{
    max-width:100%;
  }
</style>
  <h1>index</h1>
  <div id="movie-box">
    
  </div>
  <button id="movie-btn">영화데이터</button>


  <button id="data-btn">데이터받기</button>

  <div class="pagination">
    <div>1</div>
    <div>2</div>
    <div>3</div> 
    <div>4</div>
    <div>5</div>
    <div>6</div>
    <div>7</div>
  </div>
  <div id="data-value"></div>

{% endblock content %}

{% block script %}
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    const dataBtn = document.querySelector('#data-btn');
    const dataValue = document.querySelector('#data-value');
    const movieBtn = document.querySelector('#movie-btn');
    const movieTitle = document.querySelector('#movie-title');

   
    window.onload = function() {
      console.log('@@@@@@@@llload')
      getMovies();
    }


    dataBtn.addEventListener('click', function (event) {
      event.preventDefault();
      axios({
        method: 'get', 
        url: '/movies/data/'
      })
      .then((response) => {
        console.log(response.data.movies['일']);
        dataValue.innerText = response.data.movies['삼'];
      });
    })
    
    const btn2 = document.querySelector('#btn2');
    const btns = document.querySelectorAll('.pagination div');


    function getMovies(event){
      const API_KEY = `30b3f55a2d2aa951c4ef256c10f8cef9`;

      
      let pageNumber = event?event.target.innerText:1;
      axios({
        method:'get',
        url:`https://api.themoviedb.org/3/movie/popular?api_key=${API_KEY}&language=ko-KR&page=${pageNumber}`
      })
      .then(res=>{
        if (document.querySelector("#movie-title")) {
          document.querySelector("#movie-title").remove()
        }
        const movies = res.data.results;
        const movieBox = document.querySelector("#movie-box")
        const movieTitle = document.createElement("div");
        movieTitle.setAttribute('id', 'movie-title')
        movieBox.appendChild(movieTitle);
        
        movies.forEach((movie,index)=>{
          const newDiv = document.createElement("div");
          const changeIndex = (pageNumber * 20) - 20;
          const POSTER_URL = `https://image.tmdb.org/t/p/w500` + movie.poster_path;
          const imgElement = document.createElement("img");
          imgElement.setAttribute('src',POSTER_URL);
          
          newDiv.innerText = `${changeIndex + index+1} : ${movie.title}`;
          newDiv.append(imgElement);
          movieTitle.appendChild(newDiv);
        });
      });
    }
    movieBtn.addEventListener('click', getMovies);

    btns.forEach((btn) => {
      console.log('@@@@@@@@@@',btn)
      btn.addEventListener('click', getMovies);
    })
  </script>

{% endblock script %}

Json_response/movies/templates/movies/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>update</h1>

  <form action="{% url 'movies:update' movie.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="수정하기">
  </form>
  <a href="{% url 'movies:update' movie.pk %}">
    <button>되돌리기</button>
  </a>
  <a href="{% url 'movies:index' %}">뒤로가기</a>
{% endblock content %}

Json_response/templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  </head>

  <body>
    {% if request.user.is_authenticated %}
      <h2>hello!!
        {{ user }}</h2>
      <a href="{% url 'accounts:logout' %}">로그아웃</a>
      <a href="{% url 'accounts:delete' %}">회원탈퇴</a>
      <a href="{% url 'accounts:update' %}">수정하기</a>
    {% else %}
      <a href="{% url 'accounts:login' %}">로그인</a>
      <a href="{% url 'accounts:signup' %}">회원가입</a>
    {% endif %}

    {% block content %}{% endblock content %}
    {% block script %}{% endblock script %}
  </body>

</html>